In [1]:
import pandas as pd

from scripts.utils import *

In [3]:
df = pd.read_csv("data/case_2_processed.csv")
df.head()

,chr,pos,ref,alt,driver,id,ref_len,alt_len,fetched_nucleotides,is_nucleotides_same,ref_start,ref_end,upstream_sequence,downstream_sequence,sequence,mutated_sequence,is_mirna,transcript_id,gene_name,biotype
0,17,56408612,A,T,1,17_56408612_A_T,1,1,A,True,56408612,56408613,TCTCCGAAGCCCACAGTACACTCATCCATA,AGTAGGAAACACTACACCCTCCAGTGCTGT,TCTCCGAAGCCCACAGTACACTCATCCATAAAGTAGGAAACACTAC...,TCTCCGAAGCCCACAGTACACTCATCCATATAGTAGGAAACACTAC...,1,"['ENST00000384835', 'ENST00000578334', 'ENST00...","['BZRAP1-AS1', 'MIR142']",miRNA
1,17,56408616,A,C,1,17_56408616_A_C,1,1,A,True,56408616,56408617,CGAAGCCCACAGTACACTCATCCATAAAGT,GGAAACACTACACCCTCCAGTGCTGTTAGT,CGAAGCCCACAGTACACTCATCCATAAAGTAGGAAACACTACACCC...,CGAAGCCCACAGTACACTCATCCATAAAGTCGGAAACACTACACCC...,1,"['ENST00000384835', 'ENST00000578334', 'ENST00...","['BZRAP1-AS1', 'MIR142']",miRNA
2,17,56408620,A,G,1,17_56408620_A_G,1,1,A,True,56408620,56408621,GCCCACAGTACACTCATCCATAAAGTAGGA,ACACTACACCCTCCAGTGCTGTTAGTAGTG,GCCCACAGTACACTCATCCATAAAGTAGGAAACACTACACCCTCCA...,GCCCACAGTACACTCATCCATAAAGTAGGAGACACTACACCCTCCA...,1,"['ENST00000384835', 'ENST00000578334', 'ENST00...","['BZRAP1-AS1', 'MIR142']",miRNA
3,17,56408620,AA,TG,1,17_56408620_AA_TG,2,2,AA,True,56408620,56408622,GCCCACAGTACACTCATCCATAAAGTAGGA,CACTACACCCTCCAGTGCTGTTAGTAGTGC,GCCCACAGTACACTCATCCATAAAGTAGGAAACACTACACCCTCCA...,GCCCACAGTACACTCATCCATAAAGTAGGATGCACTACACCCTCCA...,1,"['ENST00000384835', 'ENST00000578334', 'ENST00...","['BZRAP1-AS1', 'MIR142']",miRNA
4,17,56408621,A,G,1,17_56408621_A_G,1,1,A,True,56408621,56408622,CCCACAGTACACTCATCCATAAAGTAGGAA,CACTACACCCTCCAGTGCTGTTAGTAGTGC,CCCACAGTACACTCATCCATAAAGTAGGAAACACTACACCCTCCAG...,CCCACAGTACACTCATCCATAAAGTAGGAAGCACTACACCCTCCAG...,1,"['ENST00000384835', 'ENST00000578334', 'ENST00...","['BZRAP1-AS1', 'MIR142']",miRNA

In [5]:
mirna_df = pd.read_csv("data/mirbase22_grch37_coordinates.csv")
mirna_df.head()

  mirna_accession       mirna_name chr      start        end strand
0    MIMAT0027618  hsa-miR-6859-5p   1      17409      17431      -
1    MIMAT0027619  hsa-miR-6859-3p   1      17369      17391      -
2    MIMAT0005890     hsa-miR-1302   1      30438      30458      +
3    MIMAT0027618  hsa-miR-6859-5p   2  114353582  114353604      +
4    MIMAT0027619  hsa-miR-6859-3p   2  114353622  114353634      +